spring:
  datasource:
    name: pizzeria
    url: jdbc:h2:file:./h2-db/pizzeria;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    change-log: classpath:/db/master-changelog.yml